### ISSUE TITLE
Unable to resolve "ActivityIndicator" from "node_modules\react-native-bg-thread\node_modules\react-native\Libraries\react-native\react-native.js"

### ISSUE THREAD

**Issue by SanjanaTailor** [Blitz-Mobile-Apps/react-native-bg-thread#1]
Enviornment info :
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
    Memory: 1.06 GB / 7.88 GB
  Binaries:
    Node: 8.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 26.0.2, 28.0.3, 29.0.2
      System Images: android-24 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: ~16.9.0 => 16.9.0
    react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4

Facing below problem while running the app
Unable to resolve "ActivityIndicator" from "node_modules\react-native-bg-thread\node_modules\react-native\Libraries\react-native\react-native.js"
Failed building JavaScript bundle.

@alex-evans123  can you please check this  as soon as possible. Please reply thanks in an advanced
``` import React, { Component } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import RnBgTask from 'react-native-bg-thread';

export default class App extends Component {

  componentDidMount() {
    RnBgTask.runInBackground(() => {
      
    })
  }


  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
      </View>
    );
  }

}


const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});```

**Comment by alex-evans123** [comment]
Hi,
@SanjanaTailor  please install the latest version of library, the issue is now resolved, it was due to multiple version of react-native in the project

**Comment by SanjanaTailor** [comment]
Thank you @alex-evans123 , it is resolved.
Now one more problem came after that ,
null is not an object (evaluating '_reactNativeBgThread.default.runInBackground')
* http://packager.5v-w3x.anonymous.assignmentsix.exp.direct/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:123542:37 in componentDidMount

```import React, { Component } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import RnBgTask from 'react-native-bg-thread';

export default class App extends Component {
  componentDidMount() {
    RnBgTask.runInBackground(() => {
      // your js code here
    })
  }


  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
}); ```
This is for reference.
can you please help on this ?
