### ISSUE TITLE
null is not an object (evaluating '_reactNativeBgThread.default.runInBackground')

### ISSUE THREAD

**Issue by SanjanaTailor** [Blitz-Mobile-Apps/react-native-bg-thread#2]
Now one more problem came after that ,
null is not an object (evaluating '_reactNativeBgThread.default.runInBackground')
* http://packager.5v-w3x.anonymous.sample.exp.direct/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:123542:37 in componentDidMount

```
import React, { Component } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import RnBgTask from 'react-native-bg-thread';

export default class App extends Component {
  componentDidMount() {
    RnBgTask.runInBackground(() => {
      // your js code here
    })
  }


  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
}); ```
This is for reference.
can you please help on this ?

**Comment by alex-evans123** [comment]
Hi @SanjanaTailor ,
Try reinstalling the library , looks like the library is not linked properly.

**Comment by SanjanaTailor** [comment]
@alex-evans123 : can you please look above issue.. ?

**Comment by alex-evans123** [comment]
HI @SanjanaTailor ,
Are you using this library on expo project?

**Comment by SanjanaTailor** [comment]
yes @alex-evans123  using the library in expo directory

**Comment by SanjanaTailor** [comment]
@alex-evans123 :  Using this library for background thread purpose and need a solution from your end. Thank you

**Comment by alex-evans123** [comment]
@SanjanaTailor you can only use this library on project created with react-native-cli or an expo ejected project, because this library heavily depends on native code
Thank you

Closing this issue

**Comment by SanjanaTailor** [comment]
@alex-evans123 created this project using expo init and it is expo ejected and tried to re-install this library still facing same issue so on expo ejected it is not working.

**Comment by iampapagray** [comment]
> @SanjanaTailor you can only use this library on project created with react-native-cli or an expo ejected project, because this library heavily depends on native code
> Thank you
> 
> Closing this issue

I have the same error and i am not using expo. I just installed the library though. I've got version 1.1.6

**Comment by iampapagray** [comment]
I have fixed the error by fixing the typo mentioned in the pull request

**Comment by SanjanaTailor** [comment]
okay, yes it worked using react native cli.
