### ISSUE TITLE
Didn't get the point

### ISSUE THREAD

**Issue by matheus-rosin** [Blitz-Mobile-Apps/react-native-bg-thread#4]
Hi!

I tried this package in my project. I need to filter and sort a large array with plenty of calculations; and the trouble is that it blockes the UI (except screen scroll, because of `ScrollView`) - like a button press.

I tried to call the function that does that job inside `runInBackground` but nothing changed. So what's the point of the library? Maybe I am using this the wrong way, but I don't believe it.

Thanks!

**Comment by alex-evans123** [comment]
The library makes use of NSOperationQueue on ios and standard runnable and thread classes on android.

However the performance still depends on the processor speed and RAM of the phone you're using and the effects can only be seen in release build as on debug the js is executed in browser instance of computer and not in the phone.

To get the most of it make sure that you are using it outside of the render method

**Comment by alex-evans123** [comment]
Closing this issue, as it is not an issue.

**Comment by stacksideflow** [comment]
> Hi!
> 
> I tried this package in my project. I need to filter and sort a large array with plenty of calculations; and the trouble is that it blockes the UI (except screen scroll, because of `ScrollView`) - like a button press.
> 
> I tried to call the function that does that job inside `runInBackground` but nothing changed. So what's the point of the library? Maybe I am using this the wrong way, but I don't believe it.
> 
> Thanks!

valid concern, https://github.com/Blitz-Mobile-Apps/react-native-bg-thread/issues/5
