### ISSUE TITLE
No multiprocessing is possible

### ISSUE THREAD

**Issue by stacksideflow** [Blitz-Mobile-Apps/react-native-bg-thread#5]
Looking at the Obj-C code in this repo, it doesn't really look like any multithreading is involved. The thing is that the function never leaves main JS call stack and thus it blocks (as it is expected in JS context) until it is executed in the event loop.

**Comment by benjaminlogan420** [comment]
Hi @stacksideflow ! 
We recently released the update of this package in which we added thread priority control and some changes were made to the objective-C code in which we worked on a better-approach to achieve enhanced background threading. The package now uses NSThread class in objective-C and standard Thread class in java.
Following is the link for the latest commit: 
[https://github.com/Blitz-Mobile-Apps/react-native-bg-thread/commit/8ed1e2602eaadd491747fb35b12df84be8d04866](url)

react-native-bg-thread v1.1.8 is the latest version of this package on npm.
[https://www.npmjs.com/package/react-native-bg-thread](url)

In case of any issues and concerns, feel free to reach out. Any suggestions or feature requests are highly welcomed. 
Contact me on: [benjaminlogan420@gmail.com](url)
