### ISSUE TITLE
License for distribution 

### ISSUE THREAD

**Issue by DanyGZ** [Blitz-Mobile-Apps/react-native-bg-thread#8]
Hi, currently we are working on a react-native project. In our project we are using this library to perform some tasks inside our application. In order to continue with the project and distribute the app, we need the license of usage for your library. Can you please upload the license?
Thanks

**Comment by benjaminlogan420** [comment]
Hi @DanyGZ  ! 
Following is the link for anyone who wants to add our license, if needed.
[MIT License ](https://github.com/Blitz-Mobile-Apps/react-native-bg-thread/blob/master/LICENSE.txt)
